name: Build Logstash Docker Image

on:
  workflow_dispatch:
    inputs:
      logstash_version:
        description: 'Logstash version to build'
        required: true
        default: '8.16.0'
        type: string
      postgres_driver_version:
        description: 'PostgreSQL JDBC driver version'
        required: true
        default: '42.7.4'
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/logstash-postgres

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.logstash_version }}-pg${{ github.event.inputs.postgres_driver_version }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            LOGSTASH_VERSION=${{ github.event.inputs.logstash_version }}
            POSTGRES_DRIVER_VERSION=${{ github.event.inputs.postgres_driver_version }}
